---
title: "Age vs Height"
subtitle: "⚔<br/> made with xaringan"
author: "Tanmay Agarwal"
institute: "Univerty of British Columbia"
date: "October 1 2022"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

## Creating a vector of age

The age of five subjects are given as follows :

-   5

-   8

-   12

-   15

-   4

```{r Age of subjects}
# Defining the age of five subjects
age <- c(5, 8, 12, 15, 4)
age
```

---

## Creating a vector of height

The height of five subjects are given as follows:

-   110

-   127

-   140

-   165

-   103

```{r Height of subjects}
# Defining the age of five subjects
height <- c(110, 127, 140, 165, 103)
height
```

---

# Plotting the Age vs Height Plot

```{r Age vs Height Graph}

plot(age, height)
```

---

class: center, middle

# Thanks for seeing the presentation!

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).

The chakra comes from [remark.js](https://remarkjs.com), [**knitr**](https://yihui.org/knitr/), and [R Markdown](https://rmarkdown.rstudio.com).
